### ISSUE TITLE
[MDEPLOY-167] Occasionally deploy fails "Failed to deploy metadata: Could not transfer metadata "

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#167]
**[Jigar Joshi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jigar.joshi)** opened **[MDEPLOY-167](https://issues.apache.org/jira/browse/MDEPLOY-167?redirect=false)** and commented

Maven deploy fails occasionally with following error message

```
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to deploy metadata: Could not transfer metadata 
```

- user has permission to connect to nexus with scp all the time
- nexus is running all the time
- nexus isn't running out of disk space

According to this thread :http://mail-archives.apache.org/mod_mbox/maven-users/201101.mbox/%3C1294417752462-3332094.post@n5.nabble.com%3E

It could be related to legacy format of metadata, which could be the case, tried passing

```
-Dmaven.metadata.legacy=true
```

still it fails occasionally

```
Caused by: org.apache.maven.wagon.TransferFailedException: Error occurred while deploying '<removed>/maven-metadata.xml' to remote repository: scp://<removed>/home/<removed>/sonatype-work/nexus/storage/snapshots: Unexpected end of data
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.providers.ssh.jsch.ScpWagon.handleIOException(ScpWagon.java:416)
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.providers.ssh.jsch.ScpWagon.finishPutTransfer(ScpWagon.java:108)
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:423)
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:402)
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:376)
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:163)
build	13-Sep-2013 13:17:15		at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:811)
build	13-Sep-2013 13:17:15		... 22 more
build	13-Sep-2013 13:17:15	Caused by: java.io.IOException: Unexpected end of data
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.providers.ssh.jsch.ScpWagon.checkAck(ScpWagon.java:130)
build	13-Sep-2013 13:17:15		at org.apache.maven.wagon.providers.ssh.jsch.ScpWagon.finishPutTransfer(ScpWagon.java:100)
```

(some of) other posts about this issue:

- http://forums.jfrog.org/Maven-fails-to-deploy-occationally-Could-not-transfer-metadata-quot-Access-denied-to-quot-error-td6713183.html

- http://mojo.10943.n7.nabble.com/Problem-to-release-perform-td40059.html

I would be ready to provide more helpful information if required

---

**Affects:** 2.7

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Could it be that 2 different projects, which share this `maven-metadata.xml`, are being uploaded at the same time?
Have you checked https://jira.codehaus.org/browse/WAGON ?
We somehow need to be able to reproduce it, so yes: some more info would help.

**Comment by jira-importer** [comment]
**[Jigar Joshi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jigar.joshi)** commented

It very well could be possible, build machine runs multiple build one of them deploys build and one of them deploys source, it could be the worst case scenario where both collides on the same file upload at the same time

checked the log and it looks very close to it

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I see something else: are you connection to a Nexus repository by scp instead of http? Then there's no way for Nexus to manage this. A repository manager should be able to prevent this kind of actions.
Since you're writing directly to the OS, you might want to try to increase [retryFailedDeploymentCount](http://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#retryFailedDeploymentCount), although I'm not sure if the file is already damaged.

**Comment by jira-importer** [comment]
**[Jigar Joshi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jigar.joshi)** commented

not a deploy plugin issue, closing it

Going to assume that nexus web end point manages synchronization to write to disk (until it fails again)

Thanks!
