### ISSUE TITLE
[MDEPLOY-174] [REGRESSION] url not required anymore, causing a NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#170]
**[Markus Karg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkarg)** opened **[MDEPLOY-174](https://issues.apache.org/jira/browse/MDEPLOY-174?redirect=false)** and commented

My POM.xml is rather empty, mostly contains only this:

```xml
<plugin>
  <artifactId>maven-deploy-plugin</artifactId>
  <version>2.8.1</version>
  <configuration>
    <groupId>${project.groupId}</groupId>
    <artifactId>${project.artifactId}</artifactId>
    <version>${project.version}</version>
    <packaging>zip</packaging>
    <file>../target/dist/DITA-OT2.0.M1_minimal_bin.zip</file>
  </configuration>
  <executions>
    <execution>
      <phase>deploy</phase>
      <goals>
        <goal>deploy-file</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

When I do "mvn -X deploy" the result is a crash of Maven:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file (default) on project dita-ot-minimal: Execution default of goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file (default) on project dita-ot-minimal: Execution default of goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file failed.
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
 at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
 at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file failed.
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
 ... 19 more
Caused by: java.lang.NullPointerException
 at org.apache.maven.artifact.repository.MavenArtifactRepository.protocol(MavenArtifactRepository.java:219)
 at org.apache.maven.artifact.repository.MavenArtifactRepository.<init>(MavenArtifactRepository.java:79)
 at org.apache.maven.repository.legacy.repository.DefaultArtifactRepositoryFactory.createArtifactRepository(DefaultArtifactRepositoryFactory.java:129)
 at org.apache.maven.repository.legacy.repository.DefaultArtifactRepositoryFactory.createDeploymentArtifactRepository(DefaultArtifactRepositoryFactory.java:78)
 at org.apache.maven.artifact.repository.DefaultArtifactRepositoryFactory.createDeploymentArtifactRepository(DefaultArtifactRepositoryFactory.java:67)
 at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:233)
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
 ... 20 more
[ERROR]
```

---

**Affects:** 2.8.1

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This configuration smells... you want to use the GAV of this project and you refer to a file outside this project.
`DITA-OT2.0.M1_minimal_bin.zip` seems final to me, so why upload it every time as part of some build lifecycle and even with different groupId/artifactId/version?

**Comment by jira-importer** [comment]
**[Markus Karg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkarg)** commented

This POM is not part of a regular lifecycle but was written to provide a simple means for a non-Maven-aware project manager to upload to Maven Central manually. It shall spare him from the need to type in the parameters needed for deploy:deploy-file. He actually builds using ANT currently. When he wants to release finally, he modifies the version number POM by hand, then invokes "mvn deploy" when he wants to publish the final release. This is a first step toward replacing ANT by Maven, which will need several weeks of work due to the complexity of the ANT build. We started by providing him this one, as publishing to Maven Central is the sole thing his ANT script does not do currently.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

What's the value for [url](http://maven.apache.org/plugins/maven-deploy-plugin/deploy-file-mojo.html#url)?

**Comment by jira-importer** [comment]
**[Markus Karg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkarg)** commented

Weird. I checked the POM and the effective POM. The URL is not specified. But instead of complaining the missing URL parameter, it says this (when executed without -X; using -X you see above error message):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file (default) on project dita-ot-minimal: Execution default of goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy-file failed. NullPointerException -> [Help 1]
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

lowering this to minor. I would expect url to be required. Let me check the svn logs to see if there is evidence why it is not (yet) required.

**Comment by jira-importer** [comment]
**[Markus Karg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkarg)** commented

Sorry for letting you wait.

What exactly do you want me to do / to post)? Instructions please. :-)

Thanks
-Markus

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I found the cause: [DeployFileMojo.java@rev1354969](http://svn.apache.org/viewvc/maven/plugins/trunk/maven-deploy-plugin/src/main/java/org/apache/maven/plugin/deploy/DeployFileMojo.java?r1=1354969&r2=1354968&pathrev=1354969) was a translation from javadoclettags to annotations (MDEPLOY-151)
The url suddenly misses it's required marker. I'll add it.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [r1568656](http://svn.apache.org/r1568656)

**Comment by jira-importer** [comment]
**[Jordan Zimmerman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt)** commented

When will there be a release of 2.9? This is a blocker for me.
