### ISSUE TITLE
[MDEPLOY-100] deploy:deploy-file fails from windows powershell

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#259]
**[snambi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snambi)** opened **[MDEPLOY-100](https://issues.apache.org/jira/browse/MDEPLOY-100?redirect=false)** and commented

mvn deploy:deploy-file fails with authentication error when tried from windows powershell.

The same command works from fine from normal windows command shell

---

**Issue Links:**
- [MINSTALL-67](https://issues.apache.org/jira/browse/MINSTALL-67) Maven does not recognize the version number provided for install-file in Windows CMD or PowerShell

**Comment by jira-importer** [comment]
**[snambi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snambi)** commented

This is the stack trace, when run from windows powershell.

It throws the error "maven-http-plugin" not found.
this plugin is in the repository.

hen executed from bash, windows cmd shell or cygwin , mvn deploy:deploy-file works just fine.

PS C:\> mvn -X deploy:deploy-file -Durl=dav:http://repository.corp.ebay
.com/bluewolf/snapshots -DrepositoryId=bluewolf -Dfile=ZXTM-API-eBay-1.0.jar -DpomFile=ZXTM-API-eBay-1.0.pom
+ Error stacktraces are turned on.
  Maven version: 2.0.9
  Java version: 1.5.0
  OS name: "windows server 2003" version: "5.2 build 3790 service pack 2" arch: "x86" Family: "dos"
  [DEBUG] Building Maven user-level plugin registry from: 'C:\Documents and Settings\djaisinghani\.m2\plugin-registry.xml'

[DEBUG] Building Maven global-level plugin registry from: 'C:\ebox\maven-2.0.9\bin\..\conf\plugin-registry.xml'
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'deploy'.
[DEBUG] Loading plugin prefixes from group: com.ebay.ebox.plugins
[DEBUG] Skipping disabled repository ebox.snapshots
[DEBUG] Loading plugin prefixes from group: org.mortbay.jetty
[DEBUG] Skipping disabled repository ebox.snapshots
[DEBUG] Loading plugin prefixes from group: org.codehaus.mojo
[DEBUG] Skipping disabled repository ebox.snapshots
[DEBUG] Loading plugin prefixes from group: org.sonatype.maven.plugins
[DEBUG] Skipping disabled repository ebox.snapshots
[DEBUG] Loading plugin prefixes from group: org.apache.maven.plugins
[DEBUG] Skipping disabled repository ebox.snapshots
[DEBUG] Retrieving parent-POM: org.apache.maven.plugins:maven-plugins::7 for project: null:maven-deploy-plugin:maven-plu
gin:2.3 from the repository.
[DEBUG] Retrieving parent-POM: org.apache.maven:maven-plugin-surrogate-parent::5 for project: org.apache.maven.plugins:m
aven-plugins:pom:7 from the repository.
[DEBUG] Retrieving parent-POM: org.apache:apache::3 for project: org.apache.maven:maven-plugin-surrogate-parent:pom:5 fr
om the repository.
[INFO] Searching repository for plugin with prefix: 'http'.
[DEBUG] Loading plugin prefixes from group: com.ebay.ebox.plugins
[DEBUG] Loading plugin prefixes from group: org.mortbay.jetty
[DEBUG] Loading plugin prefixes from group: org.codehaus.mojo
[DEBUG] Loading plugin prefixes from group: org.sonatype.maven.plugins
[DEBUG] Loading plugin prefixes from group: org.apache.maven.plugins
[DEBUG] Skipping disabled repository ebox.snapshots
[DEBUG] maven-http-plugin: using locally installed snapshot
[DEBUG] Artifact not found - using stub model: Unable to determine the latest version

org.apache.maven.plugins:maven-http-plugin:pom:LATEST

[DEBUG] Using defaults for missing POM org.apache.maven.plugins:maven-http-plugin:pom:LATEST
[DEBUG] maven-http-plugin: using locally installed snapshot
[DEBUG] Artifact not found - using stub model: Unable to determine the release version

org.apache.maven.plugins:maven-http-plugin:pom:RELEASE

[DEBUG] Using defaults for missing POM org.apache.maven.plugins:maven-http-plugin:pom:RELEASE
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The plugin 'org.apache.maven.plugins:maven-http-plugin' does not exist or no valid version could be found
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: The plugin 'org.apache.maven.plugins:maven-http-plugin' does not
exist or no valid version could be found
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1542)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.segmentTaskListByAggregationNeeds(DefaultLifecycleExecuto
r.java:405)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:615)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.version.PluginVersionNotFoundException: The plugin 'org.apache.maven.plugins:maven-ht
tp-plugin' does not exist or no valid version could be found
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersionManager.
java:229)
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersionManager.
java:91)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:171)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1274)
... 14 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Apr 14 13:11:12 PDT 2009
[INFO] Final Memory: 2M/8M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The Powershell treats the equal sign (=) as a special/meta character. You need to escape or quote it, e.g.

```
mvn -X deploy:deploy-file "-Durl=dav:http://repository.corp.ebay"
```
