### ISSUE TITLE
[MDEPLOY-81] NPE when deploying to remote repo

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#264]
**[Graeme Steyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=steyng)** opened **[MDEPLOY-81](https://issues.apache.org/jira/browse/MDEPLOY-81?redirect=false)** and commented

When deploying multiple artifacts to a remote repository a NPE is generated if not all of the deploy commands have -DgeneratePom=true.  For example:

mvn deploy:deploy-file -DgroupId=groupid -DartifactId=sampleArtifactId -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true -Dfile=sample.jar -DrepositoryId=test dav:http://server/repository/test

mvn deploy:deploy-file -DgroupId=groupid -DartifactId=sampleArtifactId -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=false -Dfile=sample-javadoc.jar -Dclassifier=javadoc -DrepositoryId=test dav:http://server/repository/test

This results in the first command executing correctly and the second failing with:

[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at hidden.org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:919)
at org.apache.maven.project.artifact.ProjectArtifactMetadata.storeInLocalRepository(ProjectArtifactMetadata.java:86)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:437)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:86)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:239)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

This is similar to NMAVEN-130.

---

**Affects:** 2.3

**Issue Links:**
- [MDEPLOY-84](https://issues.apache.org/jira/browse/MDEPLOY-84) NPE when deploy-file with generatePom=false
 (_**"duplicates"**_)

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Marc Lustig](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=axismundi)** commented

I get the same error, deploying from windows xp to Archiva 1.0.1
