### ISSUE TITLE
[MDEPLOY-46] "mvn -DaltDeploymentRepository=... deploy" of a  SNAPSHOT doesn't replace date.buildnumber

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#309]
**[Geoffrey De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ge0ffrey.desmet)** opened **[MDEPLOY-46](https://issues.apache.org/jira/browse/MDEPLOY-46?redirect=false)** and commented

I 've checkouted a m2 project (spring-richclient) and deployed it to my local repo using the altDeploymentRepository parameter (from MDEPLOY-41).

But the checkout is a SNAPSHOT version and the deployer should replace it with something like spring-richclient-core-0.3.0-20070101.160450-2.jar
like the mvn deploy without altDeploymentRepository does,
but it doesn't:

[INFO] [deploy:deploy]
altDeploymentRepository = ggg-dev::default::scp://mvn.ggg.be/maven/maven2/dev
[INFO] Using alternate deployment repository ggg-dev::default::scp://mvn.ggg.be/maven/maven2/dev
[INFO] Retrieving previous build number from ggg-dev
Uploading: scp://mvn.ggg.be/maven/maven2/dev/org/springframework/richclient/spring-richclient-core/0.3.0-SNAPSHOT/spring-richclient-core-0.3.0-SNAPSHOT.jar
50K uploaded

---

**Affects:** 2.3

**Attachments:**
- [MDEPLOY-46.patch](https://issues.apache.org/jira/secure/attachment/12715274/MDEPLOY-46.patch) (_660 bytes_)

**Issue Links:**
- [MDEPLOY-41](https://issues.apache.org/jira/browse/MDEPLOY-41) Deploying to alternate repo specified by -DrepositoryId=

**Remote Links:**
- [GitHub Pull Request #273
](https://github.com/apache/maven-deploy-plugin/issues/273)

6 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Geoffrey De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ge0ffrey.desmet)** commented

One of the modules had NullPointerException in it, but according to WAGONSSH-49 that's an independend issue:

[INFO] Using alternate deployment repository ggg-dev::default::scp://mvn.ggg.be/maven/maven2/dev
[INFO] Retrieving previous build number from ggg-dev
Uploading: scp://mvn.ggg.be/maven/maven2/dev/org/springframework/richclient/spring-richclient/0.3.0-SNAPSHOT/spring-richclient-0.3.0-SNAPSHOT.pom
37K uploaded
Exception in thread "Exec thread mvn.ggg.be" java.lang.NullPointerException
at com.jcraft.jsch.ChannelSession.run(Unknown Source)
at java.lang.Thread.run(Thread.java:619)

**Comment by jira-importer** [comment]
**[Geoffrey De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ge0ffrey.desmet)** commented

Even setting -DupdateReleaseInfo=true doesn't help, try it yourself:

mvn deploy -DaltDeploymentRepository=ggg-deploy::default::file:///D:/tmp/delete/repo/ -DupdateReleaseInfo=true

**Comment by jira-importer** [comment]
**[Geoffrey De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ge0ffrey.desmet)** commented

-DupdateReleaseInfo=true doesn't even seem to work on a normal:
mvn deploy -DupdateReleaseInfo=true
with pom
\<repository>
\<id>ggg-deploy\</id>
\<name>gggDeployment Repository\</name>
\<url>file:///D:/tmp/delete/deployrepo/\</url>
\</repository>
\<snapshotRepository>
\<id>ggg-dev\</id>
\<name>gggDevelopment Repository\</name>
\<url>file:///D:/tmp/delete/devrepo/\</url>
\</snapshotRepository>

if the version ends in -SNAPSHOT, as it creates
D:\tmp\delete\devrepo\org\springframework\richclient\spring-richclient\0.3.0-SNAPSHOT\spring-richclient-0.3.0-20070515.075943-1.pom
It should be:
...\deployrepo\.. instead of devrepo
and
not have SNAPSHOT in it's directory name.

**Comment by jira-importer** [comment]
**[mtkopone](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mikko.koponen@ri.fi)** commented

Attaching a one-liner patch to fix this issue.

I ain't no maven expert, so I really don't know if there is a valid reason to not use unique versions for alt deployment repos for some reason. If so, I suppose the altDeploymentRepository syntax could be extended to allow this flag.

**Comment by jira-importer** [comment]
**[Maria Odea B. Ching](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oching)** commented

This seems to be fixed in 2.5. Please verify so we can close this issue.

**Comment by jira-importer** [comment]
**[Stephen Connolly](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stephenc)** commented

Marking as closed as the code contains the fix and this is also not an issue if using Maven 3 (as a side effect of Maven 3 dropping support for uniqueVersion=false)
