### ISSUE TITLE
[MDEPLOY-274] Deploy archetype failed with Unauthorized error

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#394]
**[Yin Xiang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=seanyinx)** opened **[MDEPLOY-274](https://issues.apache.org/jira/browse/MDEPLOY-274?redirect=false)** and commented

 

```java
[DEBUG] Using catalog /Users/sean/.m2/repository/archetype-catalog.xml
[DEBUG] Reading the catalog /Users/sean/.m2/repository/archetype-catalog.xml
[INFO] 
[INFO] --- maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) @ athena-project-incubator ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=74, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=29, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=73, DefaultDependencyCollector.collectTime=5, DefaultDependencyCollector.transformTime=2}
[DEBUG] org.apache.maven.plugins:maven-deploy-plugin:jar:3.0.0-M1:
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.0:compile
[DEBUG]       org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[DEBUG]          org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[DEBUG]             org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.0:runtime
[DEBUG]       org.sonatype.aether:aether-impl:jar:1.7:compile
[DEBUG]          org.sonatype.aether:aether-spi:jar:1.7:compile
[DEBUG]       org.sonatype.aether:aether-api:jar:1.7:compile
[DEBUG]       org.sonatype.aether:aether-util:jar:1.7:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.14:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.2.3:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.apache.maven:maven-model:jar:3.0:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:3.0:compile
[DEBUG]    org.apache.maven.shared:maven-artifact-transfer:jar:0.10.0:compile
[DEBUG]       org.apache.maven.shared:maven-common-artifact-filters:jar:3.0.1:compile
[DEBUG]          org.apache.maven.shared:maven-shared-utils:jar:3.1.0:compile
[DEBUG]       commons-codec:commons-codec:jar:1.11:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.5:compile
[DEBUG]    commons-io:commons-io:jar:2.5:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.1.0:compile
[DEBUG] Created new class realm plugin>org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1
[DEBUG] Importing foreign packages into class realm plugin>org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1
[DEBUG]   Imported:  < project>com.github.archetype:athena-project-incubator:1.0.2-SNAPSHOT
[DEBUG] Populating class realm plugin>org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1
[DEBUG]   Included: org.apache.maven.plugins:maven-deploy-plugin:jar:3.0.0-M1
[DEBUG]   Included: org.sonatype.sisu:sisu-inject-bean:jar:1.4.2
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7
[DEBUG]   Included: org.apache.maven:maven-aether-provider:jar:3.0
[DEBUG]   Included: org.sonatype.aether:aether-util:jar:1.7
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.14
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.7.1
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.apache.maven.shared:maven-artifact-transfer:jar:0.10.0
[DEBUG]   Included: org.apache.maven.shared:maven-common-artifact-filters:jar:3.0.1
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.1.0
[DEBUG]   Included: commons-codec:commons-codec:jar:1.11
[DEBUG]   Included: commons-io:commons-io:jar:2.5
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.1.0
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1, parent: sun.misc.Launcher$AppClassLoader@55f96302]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy' with basic configurator -->
[DEBUG]   (f) altDeploymentRepository = aws-snapshots::default::http://some.repo.net/repository/maven-snapshots/
[DEBUG]   (f) altReleaseDeploymentRepository = aws-releases::default::http://some.repo.net/repository/maven-releases
[DEBUG]   (f) altSnapshotDeploymentRepository = aws-snapshots::default::http://some.repo.net/repository/maven-snapshots
[DEBUG]   (f) deployAtEnd = false
[DEBUG]   (f) offline = false
[DEBUG]   (f) project = MavenProject: com.github.archetype:athena-project-incubator:1.0.2-SNAPSHOT @ /Users/sean/Documents/dev/athena-project-incubator/pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: com.github.archetype:athena-project-incubator:1.0.2-SNAPSHOT @ /Users/sean/Documents/dev/athena-project-incubator/pom.xml]
[DEBUG]   (f) retryFailedDeploymentCount = 1
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@16afbd92
[DEBUG]   (f) skip = false
[DEBUG] -- end configuration --
[INFO] Using alternate deployment repository aws-snapshots::default::http://some.repo.net/repository/maven-snapshots
[DEBUG] Installing checksum for com.github.archetype:athena-project-incubator:maven-archetype:1.0.2-SNAPSHOT
[DEBUG] Calculating checksums for /Users/sean/.m2/repository/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-SNAPSHOT.jar
[DEBUG] Installing checksum to /Users/sean/.m2/repository/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-SNAPSHOT.jar.md5
[DEBUG] Installing checksum to /Users/sean/.m2/repository/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-SNAPSHOT.jar.sha1
[DEBUG] Using transporter WagonTransporter with priority -1.0 for http://some.repo.net/repository/maven-snapshots
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for http://some.repo.net/repository/maven-snapshots
Downloading: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/maven-metadata.xml
Downloaded: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/maven-metadata.xml (798 B at 910 B/s)
[DEBUG] Writing tracking file /Users/sean/.m2/repository/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/resolver-status.properties
Uploading: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.jar
Uploading: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.000 s
[INFO] Finished at: 2020-07-10T09:39:15+08:00
[INFO] Final Memory: 17M/237M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) on project athena-project-incubator: ArtifactDeployerException: Failed to deploy artifacts: Could not transfer artifact com.github.archetype:athena-project-incubator:jar:1.0.2-20200710.013914-2 from/to aws-snapshots::default (http://some.repo.net/repository/maven-snapshots): Failed to transfer file: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) on project athena-project-incubator: ArtifactDeployerException
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: ArtifactDeployerException
	at org.apache.maven.plugins.deploy.DeployMojo.deployProject(DeployMojo.java:201)
	at org.apache.maven.plugins.deploy.DeployMojo.execute(DeployMojo.java:159)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.maven.shared.transfer.artifact.deploy.ArtifactDeployerException: Failed to deploy artifacts: Could not transfer artifact com.github.archetype:athena-project-incubator:jar:1.0.2-20200710.013914-2 from/to aws-snapshots::default (http://some.repo.net/repository/maven-snapshots): Failed to transfer file: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.jar. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.apache.maven.shared.transfer.artifact.deploy.internal.Maven31ArtifactDeployer.deploy(Maven31ArtifactDeployer.java:126)
	at org.apache.maven.shared.transfer.artifact.deploy.internal.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:79)
	at org.apache.maven.shared.transfer.project.deploy.internal.DefaultProjectDeployer.deploy(DefaultProjectDeployer.java:190)
	at org.apache.maven.shared.transfer.project.deploy.internal.DefaultProjectDeployer.deploy(DefaultProjectDeployer.java:134)
	at org.apache.maven.plugins.deploy.DeployMojo.deployProject(DeployMojo.java:193)
	... 23 more
Caused by: org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact com.github.archetype:athena-project-incubator:jar:1.0.2-20200710.013914-2 from/to aws-snapshots::default (http://some.repo.net/repository/maven-snapshots): Failed to transfer file: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.jar. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:326)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:254)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:422)
	at org.apache.maven.shared.transfer.artifact.deploy.internal.Maven31ArtifactDeployer.deploy(Maven31ArtifactDeployer.java:122)
	... 27 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.github.archetype:athena-project-incubator:jar:1.0.2-20200710.013914-2 from/to aws-snapshots::default (http://some.repo.net/repository/maven-snapshots): Failed to transfer file: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.jar. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:283)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:320)
	... 30 more
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://some.repo.net/repository/maven-snapshots/com/github/archetype/athena-project-incubator/1.0.2-SNAPSHOT/athena-project-incubator-1.0.2-20200710.013914-2.jar. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:631)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:553)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:535)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:529)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:509)
	at org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run(WagonTransporter.java:653)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:436)
	at org.eclipse.aether.transport.wagon.WagonTransporter.put(WagonTransporter.java:419)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask(BasicRepositoryConnector.java:519)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:359)
	... 32 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

 

Deploying archetype resulted the error above while deploying artifact with packaging jar is fine. But no such issue with maven deploy plugin 2.8.2

 

 

---

**Affects:** 3.0.0-M1

**Issue Links:**
- [MDEPLOY-278](https://issues.apache.org/jira/browse/MDEPLOY-278) Input validation for repository URLs is missing rejection of 2.x style URLs

- [MDEPLOY-279](https://issues.apache.org/jira/browse/MDEPLOY-279) Missing validation of altDeploymentRepository mojo parameter
 (_**"is superceded by"**_)

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Enable debug logs on HttpClient.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Seems new plugin completely omits credentials... hence it gets 401 from server. Note: this is local instance of Sonatype Nexus with "default config" and out-of-the-box pw, so don't worry about credentials "leak".

**Good** transaction (m-d-p 2.8.2):

```
Uploading to localhost-nexus: http://localhost:8081/content/repositories/snapshots/org/test/site/1.0-SNAPSHOT/site-1.0-20201209.183108-2.jar
[DEBUG] http-outgoing-0 >> "PUT /content/repositories/snapshots/org/test/site/1.0-SNAPSHOT/site-1.0-20201209.183108-2.jar HTTP/1.1[\r][\n]"
[DEBUG] http-outgoing-0 >> "Cache-control: no-cache[\r][\n]"
[DEBUG] http-outgoing-0 >> "Cache-store: no-store[\r][\n]"
[DEBUG] http-outgoing-0 >> "Pragma: no-cache[\r][\n]"
[DEBUG] http-outgoing-0 >> "User-Agent: Apache-Maven/3.6.3 (Java 1.8.0_275; Mac OS X 10.16)[\r][\n]"
[DEBUG] http-outgoing-0 >> "Content-Length: 2044[\r][\n]"
[DEBUG] http-outgoing-0 >> "Host: localhost:8081[\r][\n]"
[DEBUG] http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
[DEBUG] http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
[DEBUG] http-outgoing-0 >> "Authorization: Basic YWRtaW46YWRtaW4xMjM=[\r][\n]"
[DEBUG] http-outgoing-0 >> "[\r][\n]"
[DEBUG] http-outgoing-0 << "HTTP/1.1 100 Continue[\r][\n]"
[DEBUG] http-outgoing-0 << "[\r][\n]"
[DEBUG] http-outgoing-0 >> "PK[0x3][0x4][\n]"
DATA CONTINUES 
```

**Bad** transaction with m-d-p 3.0.0-M1 (no other change in project, just m-d-p version) this is how transaction looks (Authorization is missing):

```
Uploading to localhost-nexus::default: http://localhost:8081/content/repositories/snapshots/org/test/site/1.0-SNAPSHOT/site-1.0-20201209.183142-3.jar
[DEBUG] http-outgoing-1 >> "PUT /content/repositories/snapshots/org/test/site/1.0-SNAPSHOT/site-1.0-20201209.183142-3.jar HTTP/1.1[\r][\n]"
[DEBUG] http-outgoing-1 >> "Cache-control: no-cache[\r][\n]"
[DEBUG] http-outgoing-1 >> "Cache-store: no-store[\r][\n]"
[DEBUG] http-outgoing-1 >> "Pragma: no-cache[\r][\n]"
[DEBUG] http-outgoing-1 >> "User-Agent: Apache-Maven/3.6.3 (Java 1.8.0_275; Mac OS X 10.16)[\r][\n]"
[DEBUG] http-outgoing-1 >> "Content-Length: 2041[\r][\n]"
[DEBUG] http-outgoing-1 >> "Host: localhost:8081[\r][\n]"
[DEBUG] http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] http-outgoing-1 >> "Expect: 100-continue[\r][\n]"
[DEBUG] http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
[DEBUG] http-outgoing-1 >> "[\r][\n]"
[DEBUG] http-outgoing-1 << "HTTP/1.1 401 Unauthorized[\r][\n]"
[DEBUG] http-outgoing-1 << "Date: Wed, 09 Dec 2020 18:31:42 GMT[\r][\n]"
[DEBUG] http-outgoing-1 << "Server: Proximity/3.5.42-SNAPSHOT[\r][\n]"
[DEBUG] http-outgoing-1 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
[DEBUG] http-outgoing-1 << "X-Content-Type-Options: nosniff[\r][\n]"
[DEBUG] http-outgoing-1 << "WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"[\r][\n]"
[DEBUG] http-outgoing-1 << "Connection: close[\r][\n]"
[DEBUG] http-outgoing-1 << "[\r][\n]" 
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks, here is a reproducer: https://github.com/cstamas/mvn-md-bug

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

That reproducer was a reproducer for something else, but got "involved" with this one as well. To adjust it, I pushed this single commit, to make it easier to use as reproducer for this issue:

https://github.com/cstamas/mvn-md-bug/commit/50e9c9fdb9efe1e5694b0b9a6d6c9a1a45aaf07b

**Comment by jira-importer** [comment]
**[Thomas Kalmár](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.kalmar)** commented

I hit the same error today, some observations:

1st difference "normal" pom project when called with deploy:deploy resolves plugin version to 2.7, archetype project to 3.0.0-M1

wenn calling deploy:deploy with `-DaltReleaseDeploymentRepository=releases::default::[https://myrepo](https://myrepo/)` i got the same 401 error
ommiting the layout parameter (removed in 3.0.0 afaik) `-DaltReleaseDeploymentRepository=releases::[https://myrepo](https://myrepo/)` works completly fine

**Comment by jira-importer** [comment]
**[Michael Kroll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mickroll)** commented

As you can see in the Examples of [Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas) above:
- good: `Uploading to localhost-nexus:`
- bad: `Uploading to localhost-nexus::default:`

[Thomas Kalmár](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.kalmar) found out, that the URL notation changed from `repositoryId::layout::url` in 2.x to `repositoryId::url` in 3.x

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Michael Kroll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mickroll), correct. Format has been simplified. See also https://github.com/apache/maven-integration-testing/commit/e59e4f1008a85bc53ca158147db85dc76c037fa0. Please verify with this change whether the issue persists.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Oh, yup, the layout has been removed... did not even notice that... still, is strange, that same CLI line (only change is m-d-p version in POM) behaves differently...

Then reporter has same problem: he provides alt destinations w/ layout.

**Comment by jira-importer** [comment]
**[Thomas Kalmár](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.kalmar)** commented

Shouldnt 3.X either fail with wrong url layout or accept old style to? at least a fat warning would be in order for the user...

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Thomas Kalmár](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.kalmar), read the release announcement, it surely contains a JIRA issue for this. Moreover, it is a major version. Committers have chosen to simplify, thus break stuff which is fine.

**Comment by jira-importer** [comment]
**[Thomas Kalmár](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.kalmar)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)  Shure, but shouldnt it either be an invalid parameter format OR an invalid URL Format? the Unauthorized error is in no way helping detect the source of breakage.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Absolutely agree. Feel free to file a bug about incorrect handling of invalid input.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Created MDEPLOY-279, IMO this issue can be closed out.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

So let me get this straight. This is not a bug because the authentication works with alt repo, but fails with the old syntax is used because the parsing is not good?

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Yes, that is correct.
