### ISSUE TITLE
[MDEPLOY-113] No longer able to deploy an artifact w/o a pom

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#445]
**[velo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=velo)** opened **[MDEPLOY-113](https://issues.apache.org/jira/browse/MDEPLOY-113?redirect=false)** and commented

According to docs I can deploy w/o pom:
http://maven.apache.org/plugins/maven-deploy-plugin/examples/disabling-generic-pom.html

Well, I could until maven-deploy-plugin 2.2.1...  
$ mvn org.apache.maven.plugins:maven-deploy-plugin:2.2:deploy-file -Durl=file://. -Dfile=3rdparty.jar -DgroupId=com.my.3rdparty.provider -DartifactId=3rdparty-lib -Dversion=1.0 -Dpackaging=jar -DgeneratePom=false -e -DrepositoryId=jukinha

after 2.2 I go the following error:

```
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
Downloading: http://localhost:8084/nexus/content/groups/all/org/apache/maven/plugins/maven-deploy-plugin/2.2.1/maven-deploy-plugin-2.2.1.pom

Downloading: http://localhost:8084/nexus/content/groups/all/org/apache/maven/plugins/maven-deploy-plugin/2.2.1/maven-deploy-plugin-2.2.1.jar
9K downloaded  (maven-deploy-plugin-2.2.1.jar)
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [org.apache.maven.plugins:maven-deploy-plugin:2.2.1:deploy-file] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] [deploy:deploy-file {execution: default-cli}]
Uploading: file://./com/my/3rdparty/provider/3rdparty-lib/1.0/3rdparty-lib-1.0.jar
1009K uploaded  (3rdparty-lib-1.0.jar)
[INFO] Uploading project information for 3rdparty-lib 1.0
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error installing artifact's metadata: Error while deploying metadata: Specified source file does not exist: C:\Users\Seven\.m2\repository\com\my\3rdparty\provider\
3rdparty-lib\1.0\3rdparty-lib-1.0.pom

C:\Users\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3rdparty-lib-1.0.pom (The system cannot find the file specified)
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error installing artifact's metadata: Error while deploying metadata: Specified source file does not exist: C:\Use
rs\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3rdparty-lib-1.0.pom
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error installing artifact's metadata: Error while deploying metadata: Specified source file does not exist: C:\
Users\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3rdparty-lib-1.0.pom
        at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:240)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error installing artifact's metadata: Error while deploying metadata: Specified source file doe
s not exist: C:\Users\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3rdparty-lib-1.0.pom
        at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:129)
        at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:236)
        ... 19 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataDeploymentException: Error while deploying metadata: Specified source file does not exist: C:\U
sers\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3rdparty-lib-1.0.pom
        at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:449)
        at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:113)
        ... 20 more
Caused by: org.apache.maven.wagon.TransferFailedException: Specified source file does not exist: C:\Users\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3
rdparty-lib-1.0.pom
        at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:398)
        at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:365)
        at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:163)
        at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:317)
        at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifactMetadata(DefaultWagonManager.java:236)
        at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:445)
        ... 21 more
Caused by: java.io.FileNotFoundException: C:\Users\Seven\.m2\repository\com\my\3rdparty\provider\3rdparty-lib\1.0\3rdparty-lib-1.0.pom (The system cannot find the file sp
ecified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:106)
        at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:390)
        ... 26 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Mon Sep 28 16:17:58 BRT 2009
[INFO] Final Memory: 5M/31M
[INFO] ------------------------------------------------------------------------
```

I can patch it if someone confirm that is a bug.

---

**Affects:** 2.2.1, 2.3, 2.4

**Issue Links:**
- [MDEPLOY-84](https://issues.apache.org/jira/browse/MDEPLOY-84) NPE when deploy-file with generatePom=false
 (_**"duplicates"**_)

**Remote Links:**
- [GitHub Pull Request #211
](https://github.com/apache/maven-deploy-plugin/issues/211)

**Comment by jira-importer** [comment]
**[Santosh Maskar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=smaskar)** commented

Issue is observed in 'Apache Maven 2.2.1 (r801777; 2009-08-07 00:46:01+0530)'

-Santosh
