### ISSUE TITLE
[MDEPLOY-17] Fix for illegal XML in comments DeployFileMojo.java

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#449]
**[Marcel Schutte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mschutte)** opened **[MDEPLOY-17](https://issues.apache.org/jira/browse/MDEPLOY-17?redirect=false)** and commented

mvn site on the HEAD version of maven-deploy-plugin throws an exception on some xml markup in the comments for 'repositoryId' and 'url'. As a result the documentation for the deploy:deploy-file goal is not generated.

The attached patch escapes the markup in the repositoryId comment so it becomes visible. The \<br> in the 'url' comment is changed to \<br/> to make it XML/XHTML compliant.

To test: apply patch, run mvn site on the maven-deploy-plugin, check that there are no exceptions and check that target/site/deploy-file-mojo.html exists and renders correctly (repositoryId description should contain \<id> and \<server>, url should have ' ie ( file://C:\m2-repo )' on a line of its own).

org.codehaus.doxia.parser.ParseException: Error parsing the model.
at org.codehaus.doxia.module.xdoc.XdocParser.parse(XdocParser.java:41)
at org.codehaus.doxia.DefaultDoxia.parse(DefaultDoxia.java:65)
at org.codehaus.plexus.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:232)
at org.codehaus.plexus.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:173)
at org.codehaus.plexus.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:152)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:427)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: end tag name \</td> must be the same as start tag \<id> from line 160 (position: TEXT seen ..
.\<id> under &lt;server&gt; section of settings.xml\</td>... `@160`:93)
at org.codehaus.plexus.util.xml.pull.MXParser.parseEndTag(MXParser.java:1696)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1128)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1090)
at org.codehaus.doxia.module.xdoc.XdocParser.parseXdoc(XdocParser.java:292)
at org.codehaus.doxia.module.xdoc.XdocParser.parse(XdocParser.java:37)
... 23 more
[ERROR] Error rendering C:\work\maven2\plugins\maven-deploy-plugin\target\generated-site\xdoc\deploy-file-mojo.xml: Error parsing the model.
org.codehaus.doxia.parser.ParseException: Error parsing the model.
at org.codehaus.doxia.module.xdoc.XdocParser.parse(XdocParser.java:41)
at org.codehaus.doxia.DefaultDoxia.parse(DefaultDoxia.java:65)
at org.codehaus.plexus.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:232)
at org.codehaus.plexus.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:173)
at org.codehaus.plexus.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:152)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:427)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: end tag name \</td> must be the same as start tag \<id> from line 160 (position: TEXT seen ..
.\<id> under &lt;server&gt; section of settings.xml\</td>... `@160`:93)
at org.codehaus.plexus.util.xml.pull.MXParser.parseEndTag(MXParser.java:1696)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1128)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1090)
at org.codehaus.doxia.module.xdoc.XdocParser.parseXdoc(XdocParser.java:292)
at org.codehaus.doxia.module.xdoc.XdocParser.parse(XdocParser.java:37)
... 23 more

---

**Attachments:**
- [deployfilemojo-comments.patch](https://issues.apache.org/jira/secure/attachment/12715217/deployfilemojo-comments.patch) (_703 bytes_)

**Comment by jira-importer** [comment]
**[Allan Q. Ramirez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aramirez)** commented

Applied patch.. Thanks
