### ISSUE TITLE
[MDEPLOY-120] Unable to deploy large file into Nexus 1.5.0 from Windows Server 2003 Enterprise

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#467]
**[Keith Wedinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jkwuc89)** opened **[MDEPLOY-120](https://issues.apache.org/jira/browse/MDEPLOY-120?redirect=false)** and commented

Attached to this issue are the files I am using to deploy a large file to my Nexus repository.  The file being deployed is an EXE file whose size is 22,413,688 bytes.  During deployment, the upload times out after several minutes with the stack trace below which I captured by running mvn with the -X argument.  Deploying smaller files does appear to work but I have not done enough testing to determine the threshold when deployment fails.  There is no proxy between the client OS and the Nexus server.  The steps to reproduce this on my system are below.

1. Download and unzip mavenuploadfiles.zip onto a Windows Server 2003 Enterprise system.
2. Run mavenupload.cmd to get the syntax for this command script.  The syntax message is self-explanatory.

The ZIP file also contains my copy of settings.xml, the Maven settings file I am using.

If you believe this is a Nexus 1.5.0 issue, please let me know and I will open the appropriate bug for Nexus OSS 1.5.0.

STACK TRACE BEGIN:

---

Error writing to server
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: Error transferring file
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:592)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: Error transferring file
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:240)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: Error transferring file
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:121)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:236)
... 19 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.finishPutTransfer(LightweightHttpWagon.java:213)
at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:413)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:392)
at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:365)
at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:163)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:317)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:227)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:107)
... 20 more
Caused by: java.io.IOException: Error writing to server
at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:438)
at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:450)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:981)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:367)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.finishPutTransfer(LightweightHttpWagon.java:185)
... 27 more

---

**Affects:** 2.5

**Attachments:**
- [mavenuploadfiles.zip](https://issues.apache.org/jira/secure/attachment/12715222/mavenuploadfiles.zip) (_20.94 kB_)
- [mvn1024.log](https://issues.apache.org/jira/secure/attachment/12715226/mvn1024.log) (_118.78 kB_)
- [mvn1536.log](https://issues.apache.org/jira/secure/attachment/12715271/mvn1536.log) (_119.19 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

It might be worth to try this also with Maven 2.2.0 as it uses another HTTP wagon by default that might produce different results or maybe even a more precise error message. Checking the Nexus logs for errors on the server side for such a transfer would also be helpful.

**Comment by jira-importer** [comment]
**[Keith Wedinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jkwuc89)** commented

The Nexus log is not showing any errors during the failed Maven deployment.  Using Maven 2.2.0 actually makes things worse.  Based on the small snippet below of the debug output during the upload, it appears that Maven 2.2.0 is trying to upload data beyond the end of the file.  I eventually killed the process after several minutes.

33392/21888K
33396/21888K
33400/21888K
33404/21888K
33408/21888K
33412/21888K
33416/21888K
33420/21888K
33424/21888K
33428/21888K
33432/21888K
33436/21888K
33440/21888K
33444/21888K

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> it appears that Maven 2.2.0 is trying to upload data beyond the end of the file.
> When authentication is involved, the data is effectively sent twice, first without and second with credentials. This makes the progress meter show upload of twice the file size.

**Comment by jira-importer** [comment]
**[Keith Wedinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jkwuc89)** commented

I reran the Maven 2.2.0 test and let it finish.  After several minutes, the deployment failed with the following stack trace:

62680/21888K
62684/21888K
62688/21888K
[DEBUG] Software caused connection abort: socket write error
java.net.SocketException: Software caused connection abort: socket write error
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
at java.io.BufferedOutputStream.write(BufferedOutputStream.java:105)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon$RequestEntityImplementation.writeRequest(AbstractHttpClientWagon.java:160)
at hidden.org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
at hidden.org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
at hidden.org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:446)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:330)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:280)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:262)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:172)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:107)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:236)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error deploying artifact: Software caused connection abort: socket write error

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: Software caused connection abort: socket write error
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:703)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: Software caused connection abort: socket write error
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:240)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
... 17 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: Software caused connection abort: socket write error
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:121)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:236)
... 19 more
Caused by: org.apache.maven.wagon.TransferFailedException: Software caused connection abort: socket write error
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:336)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:280)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:262)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:172)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:107)
... 20 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
at java.io.BufferedOutputStream.write(BufferedOutputStream.java:105)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon$RequestEntityImplementation.writeRequest(AbstractHttpClientWagon.java:160)
at hidden.org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
at hidden.org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
at hidden.org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:446)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:330)
... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 minutes 26 seconds
[INFO] Finished at: Fri Mar 26 15:00:11 EDT 2010
[INFO] Final Memory: 7M/13M
[INFO] ------------------------------------------------------------------------
*** ERROR *** mvn command failed with error code 1

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

btw, I am able to deploy 800M artifact with maven 2.2.1 to nexus 5.0.1 professional

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

the below link my be helpful

http://old.nabble.com/deploy-large-file-to-nexus-requires-huge-memory-td27645198.html

**Comment by jira-importer** [comment]
**[Keith Wedinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jkwuc89)** commented

Inside the Windows script I am using to upload the artifact, I tried setting MAVEN_OPTS=-Xmx1024m and the behavior was unchanged.  I also tried MAVEN_OPTS=-Xmx1536m and the behavior was also unchanged.  The results from both of these attempts are attached as mvn1024.log and mvn1536.log.

**Comment by jira-importer** [comment]
**[Keith Wedinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jkwuc89)** commented

Log files capturing failures when using -Xmx1024m and -Xmx1536m.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Maybe WAGON-381?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

No feedback, so closing it.
