### ISSUE TITLE
[MDEPLOY-196] Add support for specifying customs licenses for a generated default pom

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#476]
**[Kyle Holohan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kholohan)** opened **[MDEPLOY-196](https://issues.apache.org/jira/browse/MDEPLOY-196?redirect=false)** and commented

It would be nice to be able to specify the licenses that we want to include in the generated pom file.  Something along the lines of this:

```xml
<plugin>
  <artifactId>maven-install-plugin</artifactId>
  <configuration>
    <groupId>org.apache.maven.test</groupId>
    <artifactId>maven-install-file-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <file>${basedir}/target/test-classes/unit/install-file-basic-test/target/maven-install-test-1.0-SNAPSHOT.jar
    </file>
    <localRepository>${localRepository}</localRepository>
    <licenses>
                 <license>
                   <name>Apache License, Version 2.0</name>
                  <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
                 </license>
    </licenses>
  </configuration>
</plugin>
```

---
No further details from [MDEPLOY-196](https://issues.apache.org/jira/browse/MDEPLOY-196?redirect=false)

**Comment by jira-importer** [comment]
**[Kyle Holohan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kholohan)** commented

I was able to achieve this by:

https://github.com/kholohan/maven-plugins/commit/65083030785f91600224666da3d943e6f5981de7

However,  was getting the following exception when attempting to add this entry to target/test-classes/unit/deploy-file-test/plugin-config.xml for testing:

```java
org.codehaus.plexus.component.configurator.ComponentConfigurationException: Error loading class 'org.apache.maven.plugin.deploy.License'
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:170)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:54)
	at org.apache.maven.plugin.testing.AbstractMojoTestCase.lookupMojo(AbstractMojoTestCase.java:217)
	at org.apache.maven.plugin.testing.AbstractMojoTestCase.lookupMojo(AbstractMojoTestCase.java:133)
	at org.apache.maven.plugin.deploy.DeployFileMojoTest.testDeployTestEnvironment(DeployFileMojoTest.java:65)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.plugin.deploy.License
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:195)
	at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:255)
	at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader.java:214)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:158)
	... 29 more
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

IMHO the `install-file` goal should never be called from commandline and defined within a `pom.xml`, hence it doesn't make sense to add configuration for additional elements such as licenses.
Based on your example I wonder what you are trying to do and why you are not using the standard `install` goal as part of the build lifecycle. If you explain the reason why you want to install artifacts like this, maybe we can help you with a better approach.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No reaction from the reporter for more than year.
