### ISSUE TITLE
[MDEPLOY-90] Deploy should be allowed in offline mode when the repo is a file:

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#484]
**[AJSoft](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajsoft)** opened **[MDEPLOY-90](https://issues.apache.org/jira/browse/MDEPLOY-90?redirect=false)** and commented

When the repo being deployed to is on the same machine why should offline mode prohibit operation?

---

**Affects:** 2.3

**Attachments:**
- [deploy-offline.patch](https://issues.apache.org/jira/secure/attachment/12715223/deploy-offline.patch) (_849 bytes_)

**Issue Links:**
- [MNG-5409](https://issues.apache.org/jira/browse/MNG-5409) Support deployment in offline modefor 'file' protocol
 (_**"depends upon"**_)

**Remote Links:**
- [GitHub Pull Request #144
](https://github.com/apache/maven-deploy-plugin/issues/144)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Alon Bar-Lev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alon.barlev@gmail.com)** commented

Hello,

the deploy plugin is a useful way to pack all project artifacts into maven repository structure. It is required for example when you package an application for package manager, so you need the artifacts as maven repository locally so it can be packaged.

I see no sense in limiting deploy plugin in case of repository is at file:// protocol, as file:// is not offline.

Please support this, or allow another mechanism to create locally maven repository of project artifacts.

Methods I tried: create repository using assembly - but binaries cannot be digested, create repository using dependency plugin - but I need to explicitly build the project in unique structure and explicitly specify dependencies.

The deploy plugin is the right way to do this, it is just the offline limitation inhibit the use of it.

Please push this forward, as far as code is concerned it is trivial.

Thanks!

**Comment by jira-importer** [comment]
**[Alon Bar-Lev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alon.barlev@gmail.com)** commented

OK...
So patch is simple for deploy plugin... HOWEVER the plugin is a complete void, as the whole deployment implementation is done internally in sources that are not provided by the standard apache maven download.

Anyway, found this[1], the meaning is that unless the whole maven implementation will skip offline check if protocol is "file", it cannot be done.

So I need your help to push this forward.

Thanks,
Alon

[1] http://grepcode.com/file/repo1.maven.org/maven2/org.sonatype.aether/aether-impl/1.0/org/sonatype/aether/impl/internal/DefaultDeployer.java#116

**Comment by jira-importer** [comment]
**[Alon Bar-Lev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alon.barlev@gmail.com)** commented

Patch to deploy plugin, but it is uselss per previous comment.

**Comment by jira-importer** [comment]
**[Alon Bar-Lev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alon.barlev@gmail.com)** commented

For the record, with the patch:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8-SNAPSHOT:deploy (default-deploy) on project XXX: The repository system is in offline mode, deployment impossible
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: The repository system is in offline mode, deployment impossible
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:189)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: The repository system is in offline mode, deployment impossible
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:141)
at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:165)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:153)
... 21 more
Caused by: org.sonatype.aether.deployment.DeploymentException: The repository system is in offline mode, deployment impossible
at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:204)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:443)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:137)
... 23 more

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still persists, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
