### ISSUE TITLE
[MDEPLOY-158] deploy:deploy does not work for only Deploying artifact to Maven Remote repo

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#486]
**[Himanshu goyal](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=goyalhimanshu2006)** opened **[MDEPLOY-158](https://issues.apache.org/jira/browse/MDEPLOY-158?redirect=false)** and commented

I did a `mvn install` in the first place in order to generate artifact for my maven project.

As a second step I wanted to make a decision to only `"deploy"` the generated artifact to the remote repo using
`"mvn deploy:deploy"` command
Since the artifact is already been compiled, created inside target folders, there should not be any need to force a developer to rerun everything if we wish to only upload the artifact to remote repo.

When we execute `"mvn deploy:deploy"`, it gives the following error:

```
org.apache.maven.lifecycle.LifecycleExecutionException: The packaging for this project did not assign a file to the build artifact
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: The packaging for this project did not assign a file to the build artifact
        at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:182)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
```

---

**Attachments:**
- [mvnDeployException.jpeg](https://issues.apache.org/jira/secure/attachment/12715254/mvnDeployException.jpeg) (_1.62 MB_)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Uldis Karlovs-Karlovskis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=narcomancer)** commented

Hi all,

I see no one even tried to help this guy. I'm having exactly the same problem with any version of Maven. What I need to achieve is quite simple:
1) build artifact with mvn package
2) deploy artifact to repo with install to local repository

I'm doing it from CI and I need to do it in at least two steps. What properties should I specify or which required goals to run to get deploy:deploy working?

Regards
Uldis

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The plugin responsible for packaging the artifact (`maven-jar-plugin`,`maven-war-plugin`, etc) will attach the file(s) to the `MavenProject` instance, so that the following plugins can `install` or `deploy` these files.
It is not the `maven-install-plugin` or `maven-deploy-plugin` who has the knowlegde which files are packaged and attached.
For that reason `deploy:deploy` won't work, but `jar:jar deploy:deploy` probably would.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Added FAQ-entry [r1454838](http://svn.apache.org/r1454838)
