### ISSUE TITLE
[MDEPLOY-84] NPE when deploy-file with generatePom=false 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-deploy-plugin#495]
**[Felix Knecht](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=felixk)** opened **[MDEPLOY-84](https://issues.apache.org/jira/browse/MDEPLOY-84?redirect=false)** and commented

Following the sample from http://maven.apache.org/plugins/maven-deploy-plugin/examples/disabling-generic-pom.html results in NPE:

mvn deploy:deploy-file -Durl=file:///tmp -Dfile=/foo/bar/test.jar -DgroupId=your.groupId -DartifactId=your-artifactId  -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=false
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'deploy'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]    task-segment: [deploy:deploy-file] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] [deploy:deploy-file]
Uploading: file:///tmp/your/groupId/your-artifactId/1.0.0/your-artifactId-1.0.0.jar
0b uploaded
[INFO] Retrieving previous metadata from remote-repository
[INFO] Uploading repository metadata for: 'artifact your.groupId:your-artifactId'
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at hidden.org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:919)
at org.apache.maven.project.artifact.ProjectArtifactMetadata.storeInLocalRepository(ProjectArtifactMetadata.java:86)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:437)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:86)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:239)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:514)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:376)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Thu Sep 18 14:11:05 CEST 2008
[INFO] Final Memory: 24M/64M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.4

**Issue Links:**
- [MDEPLOY-81](https://issues.apache.org/jira/browse/MDEPLOY-81) NPE when deploying to remote repo
 (_**"is duplicated by"**_)
- [MDEPLOY-101](https://issues.apache.org/jira/browse/MDEPLOY-101) Deploying javadoc or sources file without generating POM causes NPE in VersionExpressionTransformation.transformVersions(VersionExpressionTransformation.java:203)
 (_**"is duplicated by"**_)
- [MDEPLOY-113](https://issues.apache.org/jira/browse/MDEPLOY-113) No longer able to deploy an artifact w/o a pom
 (_**"is duplicated by"**_)

**Remote Links:**
- [GitHub Pull Request #143
](https://github.com/apache/maven-deploy-plugin/issues/143)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r754784](http://svn.eu.apache.org/viewvc?view=rev&revision=754784).
